"""gen ai .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14X00n6Cu6_RkJKHxKoCXOrf6RSDXEVxu
"""

import torch
import matplotlib.pyplot as plt

# Check GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if device.type != "cuda":
    print("WARNING: GPU not found. Switch the Colab runtime to GPU for best performance.")
else:
    gpu_name = torch.cuda.get_device_name(0)
    print(f"Using GPU: {gpu_name}")

from diffusers import StableDiffusionPipeline
import torch

# Optionally: Login to Hugging Face for model weights (remove/comment if public access works)
from huggingface_hub import login
# Uncomment and add your token if needed
# login("YOUR_HF_TOKEN")

model_id = "sd2-community/stable-diffusion-2-1"
pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
)
# Place pipeline on GPU (recommended for speed)
pipe = pipe.to("cuda" if torch.cuda.is_available() else "cpu")

# Optional: enable xformers for efficient memory usage if available
try:
    pipe.enable_xformers_memory_efficient_attention()
except Exception as e:
    print(f"Could not enable xformers memory efficient attention: {e}")

print("Stable Diffusion 2.1 pipeline loaded successfully.")

# === Hyperparameter Configuration ===
prompt = "A futuristic city skyline at sunset, ultra detailed, digital art"
guidance_scales = [5, 15]                  # Try 5, 15
num_inference_steps_list = [20, 50]        # Try 20, 50
seed = 42                                  # Set to int for reproducibility, or None for random
width = 512
height = 512

print(f"Prompt: {prompt}")
print(f"Guidance scales: {guidance_scales}")
print(f"Inference steps: {num_inference_steps_list}")
print(f"Seed: {seed}")
print(f"Image size: {width}x{height}")

import matplotlib.pyplot as plt
import torch

fig, axes = plt.subplots(2, 2, figsize=(10, 10))
axes = axes.flatten()

for i, gs in enumerate(guidance_scales):
    for j, nsteps in enumerate(num_inference_steps_list):
        idx = i * 2 + j

        # Set seed for reproducibility if provided, else use random
        generator = (
            torch.manual_seed(seed) if seed is not None
            else torch.Generator(device=pipe.device).manual_seed(torch.randint(0, 2**32 - 1, (1,)).item())
        )

        with torch.autocast(pipe.device.type):
            image = pipe(
                prompt,
                width=width,
                height=height,
                guidance_scale=gs,
                num_inference_steps=nsteps,
                generator=generator
            ).images[0]

        axes[idx].imshow(image)
        axes[idx].axis("off")
        axes[idx].set_title(f"Guidance: {gs}, Steps: {nsteps}")

plt.suptitle(f"Prompt: \"{prompt}\"\nImage size: {width}x{height}", fontsize=14)
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()
